##server.port=6400

#server:
  #port: 6400

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://sql6.freemysqlhosting.net:3306/sql6683023
    username: sql6683023
    password: YZBD98wisx
  main:
    allow-bean-definition-overriding: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQL8Dialect

  application:
    name: contact-manager
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

okta:
  oauth2:
    client-id: 0oads94rs52OKcKcS5d7
    client-secret: VkKqe-mni7z4MbJhuECaV5Z19boQpVsRxgx7glIsW0TeQhhqWChemuaS2qx0AFdg
    issuer: https://dev-06098242.okta.com/oauth2/default

#url: sql6.freemysqlhosting.net ##jdbc:mysql://localhost:3306/contact_manager
#okta:
#  oauth2:
#    client:
#      # From Okta application
#      clientId: 0oads94rs52OKcKcS5d7
#      clientSecret: VkKqe-mni7z4MbJhuECaV5Z19boQpVsRxgx7glIsW0TeQhhqWChemuaS2qx0AFdg
#      # From Authorization Server's metadata
#      accessTokenUri: https://dev-06098242.okta.com/oauth2/default/v1/token #https://{yourOktaDomain}/oauth2/default/v1/token https://dev-06098242.okta.com/oauth2/default
#      userAuthorizationUri: https://dev-06098242.okta.com/oauth2/default/v1/authorize
#      scope: openid profile email
#
#
#    resource:
#      # from your Auth Server's metadata, check .well-known/openid-configuration if not in .well-known/oauth-authorization-server
#      userInfoUri: https://dev-06098242.okta.com/oauth2/default/v1/userinfo
#    sso:
#      loginPath: /authorization-code/callback


#database configuration
##spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
##spring.datasource.url=jdbc:mysql://localhost:3306/contact_manager

#spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

##spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url = jdbc:mysql://localhost:3306/testdb?useSSL=false
##spring:datasource.username=root
##spring.datasource.password=root

#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=create

##spring.jpa.hibernate.ddl-auto= update
##spring.jpa.show-sql=true

##spring.servlet.multipart.enabled=true
##spring.servlet.multipart.max-file-size=10MB
##spring.servlet.multipart.max-request-size=10MB
#octa client secret 0oads94rs52OKcKcS5d7









